name: Build and Push Docker Image

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

     
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} .
          # Replace "my-image" with the desired image name, and `github.sha` gives a unique tag for each commit.

     
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}

    
      - name: Tag and Push 'latest' image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
